# Generated by Django 4.1.1 on 2022-09-28 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_run_data',
            fields=[
                ('b_run_id', models.IntegerField(primary_key=True, serialize=False)),
                ('raw_class_position', models.SmallIntegerField()),
                ('pax_class_position', models.SmallIntegerField()),
                ('pax_time', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('location', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num_list', models.TextField()),
                ('car_model_list', models.TextField()),
                ('suggestion_list', models.TextField()),
                ('total_cone_count', models.IntegerField()),
                ('run_list', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run_data',
            fields=[
                ('run_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=7)),
                ('car_num', models.IntegerField()),
                ('driver_name', models.CharField(max_length=36)),
                ('car_model', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=7)),
                ('cones_hit', models.IntegerField()),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autocross.event')),
            ],
        ),
        migrations.CreateModel(
            name='Run_notes',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tire_pressure', models.CharField(max_length=50)),
                ('tire_wear', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('b_run_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autocross.best_run_data')),
                ('run_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autocross.run_data')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocross.profile')),
            ],
        ),
        migrations.AddField(
            model_name='best_run_data',
            name='note_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autocross.run_notes'),
        ),
        migrations.AddField(
            model_name='best_run_data',
            name='run_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autocross.run_data'),
        ),
    ]
