# Generated by Django 4.1.1 on 2022-09-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocross', '0002_alter_profile_car_model_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_cone_count',
            field=models.IntegerField(null=True),
        ),
    ]
