# Generated by Django 4.1.1 on 2022-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocross', '0004_alter_best_run_data_b_run_id_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_run_data',
            name='pax_diff_first',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='best_run_data',
            name='pax_diff_succesor',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='best_run_data',
            name='raw_diff_first',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='best_run_data',
            name='raw_diff_succesor',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='events_checked_list',
            field=models.TextField(blank=True),
        ),
    ]
