# Generated by Django 4.1.1 on 2022-11-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocross', '0005_best_run_data_pax_diff_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_run_data',
            name='cones_hit_event',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='best_run_data',
            name='three_run_avg',
            field=models.CharField(default='N/A', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run_notes',
            name='video_link',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
